### ISSUE TITLE
Would like to consider the Mac version

### ISSUE THREAD

**Issue by SONGjiemo** [mhogomchungu/media-downloader#401]
I want to consider versions for other platforms, such as the Mac version.

**Comment by mhogomchungu** [comment]
Doable and it will involve adding an entry for mac build in the below link.

https://github.com/mhogomchungu/media-downloader-git/blob/main/.github/workflows/publish.yml

**Comment by SONGjiemo** [comment]
> 可行的，它将涉及添加一个条目为mac建立在下面的链接。
> 
> https://github.com/mhogomchungu/media-downloader-git/blob/main/.github/workflows/publish.yml

Hello, I can't read this thing. I'm not a developer and don't know how to code. I hope you can provide the DMG installation package for Mac directly

**Comment by mhogomchungu** [comment]
The point i was trying to make is that i do not have a Mac and therefore i can not make Mac build locally but i can make them using github's infrastructure.

**Comment by mhogomchungu** [comment]
Download "media-downloader.img" from below link and it if it runs.

I am not sure is yt-dlp and ffmpeg need to be bundled in too or the version you have installed can be used.

**Comment by SONGjiemo** [comment]
> Download "media-downloader.img" from below link and check if it runs or not.
> 
> Yt-dlp is bundled and not sure if ffpmeg need to be bundled too.
> 
> https://github.com/mhogomchungu/media-downloader-git/releases/tag/0.0.0

The problems found are as follows
1、There is no default configuration, preferably the default is 1080 mp4
![image](https://github.com/mhogomchungu/media-downloader/assets/46627639/afc85037-646d-4ac1-b3ca-c6276b8678c3)
2、The win version can be downloaded directly from the M3U8 link. Mac can't
3、Clicking has no effect, and there is no one to configure
![image](https://github.com/mhogomchungu/media-downloader/assets/46627639/c9d73ada-324a-40a5-9ec2-540efe969a24)
4、Clicking has no effect and cannot be edited
![image](https://github.com/mhogomchungu/media-downloader/assets/46627639/2650fd59-8ebf-4378-8aef-8aeb4d2c2862)

**Comment by mhogomchungu** [comment]
Great, it works.

Lets start with youtube first.

You will get higher qualities in youtube if ffmpeg is installed. When you start Media Downloader, it will tell you if it found ffmpeg or not, and can you post the output of basic tab when the app is started so that i can see what error is shown when ffmpeg is not found.

Leaving downloading options text field empty is the same as telling yt-dlp to download the highest quality possible and you will get the highest available only when ffmpeg is detected.

The "Options" button is the one to click if you want to select a specific video resolution  you want.

**Comment by SONGjiemo** [comment]
> Great, it works.
> 
> Lets start with youtube first.
> 
> You will get higher qualities in youtube if ffmpeg is installed. When you start Media Downloader, it will tell you if it found ffmpeg or not, and can you post the output of basic tab when the app is started so that i can see what error is shown when ffmpeg is not found.
> 
> Leaving downloading options text field empty is the same as telling yt-dlp to download the highest quality possible and you will get the highest available only when ffmpeg is detected.
> 
> The "Options" button is the one to click if you want to select a specific video resolution you want.

[media-downloader] Failed to find executable "ffmpeg"v
![image](https://github.com/mhogomchungu/media-downloader/assets/46627639/6d0eba82-2b62-4c0c-b42e-2274f6f9c148)
Shows No File Found

**Comment by mhogomchungu** [comment]
Download macos version again and check if ffmpeg is now present and you can download lux binary from within Media Downloader.

**Comment by SONGjiemo** [comment]
> Download macos version again and check if ffmpeg is now present and you can download lux binary from within Media Downloader.
![image](https://github.com/mhogomchungu/media-downloader/assets/46627639/968cc12f-a035-4019-b15b-6651a7c13144)
It is not possible to download YouTube files at this time


[media-downloader] cmd: "/Users/song/Library/Application Support/media-downloader/bin/yt-dlp" "--downloader" "ffmpeg" "--ignore-config" "--no-playlist" "-o" "%(title).200s-%(id)s.%(ext)s" "--newline" "--output-na-placeholder" "NA" "-f" "bestvideo[ext=mp4][vcodec^=avc]+bestaudio[ext=m4a]/bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio/best[ext=mp4]/best" "--compat-options" "2022" "--encoding" "https://github.com/mhogomchungu/media-downloader/releases/download/2.2.0/yt-dlp-aria2c.json" "https://www.youtube.com/watch?v=w5HiVn_UDwk"
Traceback (most recent call last):
  File "/Users/song/Library/Application Support/media-downloader/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1606, in wrapper
  File "/Users/song/Library/Application Support/media-downloader/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1741, in __extract_info
  File "/Users/song/Library/Application Support/media-downloader/bin/yt-dlp/yt_dlp/extractor/common.py", line 732, in extract
  File "/Users/song/Library/Application Support/media-downloader/bin/yt-dlp/yt_dlp/extractor/common.py", line 1194, in to_screen
  File "/Users/song/Library/Application Support/media-downloader/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 924, in to_screen
  File "/Users/song/Library/Application Support/media-downloader/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 905, in _write_string
  File "/Users/song/Library/Application Support/media-downloader/bin/yt-dlp/yt_dlp/utils/_utils.py", line 1438, in write_string
LookupError: unknown encoding: https://github.com/mhogomchungu/media-downloader/releases/download/2.2.0/yt-dlp-aria2c.json
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/song/Library/Application Support/media-downloader/bin/yt-dlp/__main__.py", line 17, in <module>
  File "/Users/song/Library/Application Support/media-downloader/bin/yt-dlp/yt_dlp/__init__.py", line 1072, in main
  File "/Users/song/Library/Application Support/media-downloader/bin/yt-dlp/yt_dlp/__init__.py", line 1062, in _real_main
  File "/Users/song/Library/Application Support/media-downloader/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3572, in download
  File "/Users/song/Library/Application Support/media-downloader/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3547, in wrapper
  File "/Users/song/Library/Application Support/media-downloader/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1595, in extract_info
  File "/Users/song/Library/Application Support/media-downloader/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1627, in wrapper
  File "/Users/song/Library/Application Support/media-downloader/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1073, in report_error
  File "/Users/song/Library/Application Support/media-downloader/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 992, in trouble
  File "/Users/song/Library/Application Support/media-downloader/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 934, in to_stderr
  File "/Users/song/Library/Application Support/media-downloader/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 905, in _write_string
  File "/Users/song/Library/Application Support/media-downloader/bin/yt-dlp/yt_dlp/utils/_utils.py", line 1438, in write_string
LookupError: unknown encoding: https://github.com/mhogomchungu/media-downloader/releases/download/2.2.0/yt-dlp-aria2c.json
[media-downloader] Download Failed(ErrorCode=1)

**Comment by mhogomchungu** [comment]
The "--encoding" option you are passing to yt-dlp i suspect is causing the error you are getting.

![Screenshot_20240518_203850](https://github.com/mhogomchungu/media-downloader/assets/3496115/42b54742-7d42-42f9-a532-d8899ce0ec48)

**Comment by SONGjiemo** [comment]
> The "--encoding" option you are passing to yt-dlp i suspect is causing the error you are getting.
> 
> ![Screenshot_20240518_203850](https://private-user-images.githubusercontent.com/3496115/331820602-42b54742-7d42-42f9-a532-d8899ce0ec48.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwOTc4NjYsIm5iZiI6MTcxNjA5NzU2NiwicGF0aCI6Ii8zNDk2MTE1LzMzMTgyMDYwMi00MmI1NDc0Mi03ZDQyLTQyZjktYTUzMi1kODg5OWNlMGVjNDgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTlUMDU0NjA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWUyZTE3MmY4Y2M5MzI4M2M2Njc2M2Y4MmU3ZjdiYWIzZjVlNmNiMDNjNjE2NmE1MWYxNzc4YTA1NjExMDExZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.rLPI8kYDqaoQ5t2VvYvhOzfC2aUUJmmKcvZGV2ZEqWg)

How can I solve the problem?     Can you update the version to solve the problem?

**Comment by mhogomchungu** [comment]
You must have entered the option in a text field pointed to in the below image, clear the text field and try again to download something from youtube.

![Screenshot_20240519_131422](https://github.com/mhogomchungu/media-downloader/assets/3496115/af55c03f-af31-4ef3-aa62-4b47939c2e02)

**Comment by SONGjiemo** [comment]
> You must have entered the option in a text field pointed to in the below image, clear the text field and try again to download something from youtube.
> 
> ![Screenshot_20240519_131422](https://private-user-images.githubusercontent.com/3496115/331863673-af55c03f-af31-4ef3-aa62-4b47939c2e02.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxMTUyNjMsIm5iZiI6MTcxNjExNDk2MywicGF0aCI6Ii8zNDk2MTE1LzMzMTg2MzY3My1hZjU1YzAzZi1hZjMxLTRlZjMtYWE2Mi00YjQ3OTM5YzJlMDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTlUMTAzNjAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjIyMGIzZjQ0N2I5NWM1NzczYmEyYTI1NmMxNzE0MGEzYWVmODM2YmE4NjIyZjFiZDBkZmRhYTliNWUyNWVjNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.zWU_3lui_ZtMDvAQsFb16dneSLh5t-RusHfF-vULsrk)

Unfortunately, I don't know where to fill out the instructions. My software then you are blank. But I think it’s ok if you choose the download engine. Why do you need to fill in this superfluously? I hope it can be removed in subsequent updates.

And look forward to sending me a yt-dlp address

**Comment by mhogomchungu** [comment]
Can you also check if you can change application language? The settings is the first entry in the above image.

An updated build should also show correct version of tar.

**Comment by mhogomchungu** [comment]
There is something you did to cause Media Downloader to pass "--encoding" option to yt-dlp. If you do not remember how you did it and how to undid it, then close Media Downloader, delete a folder circled in the below image and start again Media Downloader.

Test if you can download from youtube without making any application configuration changes.

Also test if you can change application language with this being the only configuration change you make.

Its hard to make sense of what you are seeing when you make changes i do not anticipate you making.

![Screenshot_20240519_135420](https://github.com/mhogomchungu/media-downloader/assets/3496115/1ef62e44-3d13-4263-b927-767db4057aa7)

**Comment by SONGjiemo** [comment]
> There is something you did to cause Media Downloader to pass "--encoding" option to yt-dlp. If you do not remember how you did it and how to undid it, then close Media Downloader, delete a folder circled in the below image and start again Media Downloader.
> 
> Test if you can download from youtube without making any application configuration changes.
> 
> Also test if you can change application language with this being the only configuration change you make.
> 
> Its hard to make sense of what you are seeing when you make changes i do not anticipate you making.
> 
> ![Screenshot_20240519_135420](https://private-user-images.githubusercontent.com/3496115/331865732-1ef62e44-3d13-4263-b927-767db4057aa7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxMTcxMDUsIm5iZiI6MTcxNjExNjgwNSwicGF0aCI6Ii8zNDk2MTE1LzMzMTg2NTczMi0xZWY2MmU0NC0zZDEzLTQyNjMtYjkyNy03NjdkYjQwNTdhYTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTlUMTEwNjQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjRlOGY3MWIyMzIzMzg0NGI0MmZhNDgyNDJiNWNmOGE5NTIxZWRjNTQzMDc4ZDM1OGEwMWZmN2EwZTNjMjRmNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.t3G244fDnwRTiflJKSQir7QrfcT27ptKnOP4QYL9v7E)
I can't see clearly, the directory in the screenshot. Hope you copy it

**Comment by mhogomchungu** [comment]
Start Media Downloader, go to the "basic downloader" tab and then look at the "App Data Path" line and its entry  is the directory to delete.

**Comment by SONGjiemo** [comment]
> Start Media Downloader, go to the "basic downloader" tab and then look at the "App Data Path" line and its entry is the directory to delete.

has been deleted. Problem solved. I made a post beautifying your software UI. Hopefully, you'll think about the aesthetics of your UI.
https://github.com/mhogomchungu/media-downloader/issues/403

**Comment by mhogomchungu** [comment]
Yes, i have seen it and will respond later, can you check if you can change the application language.

**Comment by mhogomchungu** [comment]
I noticed something in your output that should not be there.

You are using "yt-dlp" instead of "yt-dlp_macos".

Can you do the following to test the new code.
1. Close Media Downloader.
2. Delete the "App Data Path" folder again.
3. Redownload Media Downloader.
4. Download something from youtube and check what is the name of yt-dlp binary that is used.

**Comment by SONGjiemo** [comment]
> I noticed something in your output that should not be there.
> 
> You are using "yt-dlp" instead of "yt-dlp_macos".
> 
> Can you do the following to test the new code.
> 
> 1. Close Media Downloader.
> 2. Delete the "App Data Path" folder again.
> 3. Redownload Media Downloader.
> 4. Download something from youtube and check what is the name of yt-dlp binary that is used.

I followed your steps and deleted the cache first. Went to download YouTube and found a new problem.

[media-downloader] cmd: "/Users/song/Library/Application Support/media-downloader/bin/yt-dlp" "--newline" "--ignore-config" "--no-playlist" "-o" "%(title).200s-%(id)s.%(ext)s" "--output-na-placeholder" "NA" "-f" "bestvideo[ext=mp4][vcodec^=avc]+bestaudio[ext=m4a]/bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio/best[ext=mp4]/best" "--compat-options" "2022" "--progress-template" "download:[download] downloaded_bytes:%(progress.downloaded_bytes)s ETA:%(progress.eta)s total_bytes_estimate:%(progress.total_bytes_estimate)s total_bytes:%(progress.total_bytes)s progress.speed:%(progress.speed)s filename:%(progress.filename)s" "https://www.youtube.com/watch?v=wRhqtMhC_zU&list=PL9r1366jCphKmqdj5PqtjnESvu0MrVH6Q&index=8"
[youtube:tab] Extracting URL: https://www.youtube.com/watch?v=wRhqtMhC_zU&list=PL9r1366jCphKmqdj5PqtjnESvu0MrVH6Q&index=8
[youtube:tab] Downloading just the video wRhqtMhC_zU because of --no-playlist
[youtube] Extracting URL: https://www.youtube.com/watch?v=wRhqtMhC_zU
[youtube] wRhqtMhC_zU: Downloading webpage
[youtube] wRhqtMhC_zU: Downloading ios player API JSON
[youtube] wRhqtMhC_zU: Downloading android player API JSON
WARNING: [youtube] Skipping player responses from android clients (got player responses for video "aQvGIIdgFDM" instead of "wRhqtMhC_zU")
[youtube] wRhqtMhC_zU: Downloading m3u8 information
[info] wRhqtMhC_zU: Downloading 1 format(s): 135+140
[download] Destination: 少年張三丰 第6集 （張衛健、蘇有朋、李冰冰）-wRhqtMhC_zU.f135.mp4
[download] 241.58 MiB / 241.58 MiB (100%) at 1.46 MiB/s, ETA NA
[download] Destination: 少年張三丰 第6集 （張衛健、蘇有朋、李冰冰）-wRhqtMhC_zU.f140.m4a
[download] 29.25 MiB / 41.40 MiB (70.65%) at 3.33 MiB/s, ETA 00:03
[download] Got error: EOF occurred in violation of protocol (_ssl.c:1129). Retrying (1/10)...
[download] Got error: EOF occurred in violation of protocol (_ssl.c:1129). Retrying (2/10)...
[download] Got error: EOF occurred in violation of protocol (_ssl.c:1129). Retrying (3/10)...
[download] Got error: EOF occurred in violation of protocol (_ssl.c:1129). Retrying (4/10)...
[download] Got error: EOF occurred in violation of protocol (_ssl.c:1129). Retrying (5/10)...
[download] Got error: EOF occurred in violation of protocol (_ssl.c:1129). Retrying (6/10)...
[download] Got error: EOF occurred in violation of protocol (_ssl.c:1129). Retrying (7/10)...
[download] Got error: EOF occurred in violation of protocol (_ssl.c:1129). Retrying (8/10)...
[download] Got error: EOF occurred in violation of protocol (_ssl.c:1129). Retrying (9/10)...
[download] Got error: EOF occurred in violation of protocol (_ssl.c:1129). Retrying (10/10)...
ERROR: 
[download] Got error: EOF occurred in violation of protocol (_ssl.c:1129). Giving up after 10 retries
[media-downloader] Download Failed(ErrorCode=1)

**Comment by mhogomchungu** [comment]
That is a network related problem and is not caused by Media Downloader. did you change your network configuration while downloading like changing your network to start using a proxy server?

I provide both ```media-downloader.app..zip``` and ```media-downloader.img``` for MacOS, which one do you use and why.

**Comment by SONGjiemo** [comment]
> https://github.com/mhogomchungu/media-downloader-git/releases/tag/0.0.0

![image](https://github.com/mhogomchungu/media-downloader/assets/46627639/a982d237-1237-4889-baf5-c439f9439ef6)
1. I'm not a programmer, and I don't understand where the 2 differences are. 2. In the process of use, I did not change the agent or perform other operations. I don't know why the final stage failed

**Comment by mhogomchungu** [comment]
Try to download another time and it should work when the network issue sorts itself out.

Closing this one as "fixed" and thank you for your help in making macos build possible.

**Comment by SONGjiemo** [comment]
> Try to download another time and it should work when the network issue sorts itself out.
> 
> Closing this one as "fixed" and thank you for your help in making macos build possible.

After your prompting, I switched to the proxy software. There is no problem with downloading anymore.

**Comment by mhogomchungu** [comment]
I think i am done now with MacOS support and would apprecatiate if you could do below steps again to make sure i did not break anything with changes i made after you last update

1. Close Media Downloader.
2. Delete the "App Data Path" folder again.
3. Redownload Media Downloader.
4. Post output of basic downloader when you run the app for the first time after updating.
5. Download something from youtube and post output in basic downloader tab.

**Comment by mhogomchungu** [comment]
> However, the downloaded file is the date of the video on the website and the time the video was created. The video file I want to download is the time the video is currently downloaded. I hope this can be revised.

The downloaded file will have a name specified in the "-o" option, if its different from what you want then you can change it by changing the "-o" option.

Default downloaded file name should be in the format of ```TITLE-ID.EXTENSION```

**Comment by SONGjiemo** [comment]
> > However, the downloaded file is the date of the video on the website and the time the video was created. The video file I want to download is the time the video is currently downloaded. I hope this can be revised.
> 
> The downloaded file will have a name specified in the "-o" option, if its different from what you want then you can change it by changing the "-o" option.
> 
> Default downloaded file name should be in the format of `TITLE-ID.EXTENSION`

![image](https://github.com/mhogomchungu/media-downloader/assets/46627639/6eb7a7c2-96eb-4bda-9e9b-f32501e999f6)
I'm talking about the timing of this file after the video is downloaded. This is the time when the video address was obtained, not the time when the video was downloaded to the computer.

**Comment by mhogomchungu** [comment]
Hi, could you please look at below issue and assist please, If you got the same error then how did you solve it?

https://github.com/mhogomchungu/media-downloader/issues/406
